apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - image: docker.io/yadagiri/vote
        name: vote-ui
        ports:
        - containerPort: 80
 stage('Trigger deployment') {
      agent any
      environment{
        def GIT_COMMIT = "${env.GIT_COMMIT}"
      }
      steps{
        echo "${GIT_COMMIT}"
        echo "triggering deployment"
        // passing variables to job deployment run by github.com/eeganlf/vote-deploy/blob/master/Jenkinsfile
        build job: 'deployment', parameters: [string(name: 'DOCKERTAG', value: GIT_COMMIT)]
      }    
   }
